# Generated by Django 3.2.10 on 2023-05-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryDB',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=50)),
                ('AuthorName', models.CharField(max_length=50)),
                ('Pub_Date', models.DateField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=100)),
            ],
        ),
    ]
